database:
  name: company_project
  databaseName: company_project
  plan: free

services:
  - type: web
    name: be-backend
    runtime: docker
    dockerfilePath: ./BE/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DDL_AUTO
        value: validate
      - key: RENDER
        value: "true"
