-- ============================================================================
-- GEMINI ERP - PRODUCTION-GRADE POSTGRESQL DATABASE INITIALIZATION & SCHEMA DDL
-- File: 01_setup.sql
-- Description: Creates the full PostgreSQL schema explicitly (converting NVARCHAR
--              to standard VARCHAR/TEXT) to bypass Hibernate T-SQL limitations on startup.
-- Target Company: Tech Corp (Enterprise Plan, company_id = 1)
-- ============================================================================

-- 1. DROP EXISTING TABLES IN CASCADE ORDER TO ENSURE A CLEAN SLATE
DROP TABLE IF EXISTS time_logs CASCADE;
DROP TABLE IF EXISTS issue_comments CASCADE;
DROP TABLE IF EXISTS issue_activities CASCADE;
DROP TABLE IF EXISTS issues CASCADE;
DROP TABLE IF EXISTS sprints CASCADE;
DROP TABLE IF EXISTS project_phases CASCADE;
DROP TABLE IF EXISTS project_members CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS leave_requests CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS company_member_roles CASCADE;
DROP TABLE IF EXISTS company_members CASCADE;
DROP TABLE IF EXISTS company_settings CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS issue_statuses CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS calendar_events CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS project_expenses CASCADE;
DROP TABLE IF EXISTS workspace_join_requests CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS project_goals CASCADE;
DROP TABLE IF EXISTS issue_custom_fields CASCADE;
DROP TABLE IF EXISTS issue_custom_field_values CASCADE;
DROP TABLE IF EXISTS issue_dependencies CASCADE;
DROP TABLE IF EXISTS resource_allocations CASCADE;
DROP TABLE IF EXISTS salary_proposals CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS login_attempts CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS global_settings CASCADE;
DROP TABLE IF EXISTS event_attendees CASCADE;

-- ============================================================================
-- 2. EXPLICIT POSTGRESQL DDL CREATION (Bypasses NVARCHAR error in Hibernate)
-- ============================================================================

CREATE TABLE users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    avatar_data TEXT,
    email varchar(100) UNIQUE,
    fcm_token varchar(500),
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    is_online boolean NOT NULL DEFAULT false,
    is_system_admin boolean NOT NULL DEFAULT false,
    last_login timestamp(6),
    last_seen timestamp(6),
    phone_number varchar(15),
    presence_status varchar(20) DEFAULT 'ONLINE',
    two_factor_backup_codes varchar(500),
    two_factor_enabled boolean DEFAULT false,
    two_factor_secret varchar(255),
    username varchar(50) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    full_name varchar(100) DEFAULT NULL,
    status varchar(30) DEFAULT 'ACTIVE',
    activation_token varchar(100),
    reset_password_token varchar(100),
    reset_password_token_expiry timestamp(6),
    notif_email_new_message boolean DEFAULT true,
    notif_email_mentions boolean DEFAULT true,
    notif_email_weekly_digest boolean DEFAULT false,
    notif_push_desktop boolean DEFAULT true,
    notif_push_mobile boolean DEFAULT true,
    notif_sound_enabled boolean DEFAULT true,
    notif_email_project_updates boolean DEFAULT true
);

CREATE TABLE companies (
    company_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    name varchar(255) NOT NULL,
    description varchar(1000),
    slug varchar(100) NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true,
    email varchar(255),
    phone varchar(50),
    address varchar(500),
    subscription_plan varchar(30) NOT NULL,
    logo_data text,
    firebase_synced boolean DEFAULT false
);

CREATE TABLE company_settings (
    company_id bigint PRIMARY KEY REFERENCES companies(company_id) ON DELETE CASCADE,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    auto_review_enabled boolean DEFAULT false,
    review_cycle_type varchar(30) DEFAULT 'QUARTERLY',
    google_drive_access_token varchar(500),
    google_drive_refresh_token varchar(500),
    drive_folder_id varchar(255)
);

CREATE TABLE company_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    is_active boolean NOT NULL DEFAULT true,
    joined_at timestamp(6) NOT NULL,
    permissions TEXT DEFAULT '{}',
    firebase_synced boolean DEFAULT false
);

CREATE TABLE company_member_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id bigint NOT NULL REFERENCES company_members(id) ON DELETE CASCADE,
    role varchar(30) NOT NULL
);

CREATE TABLE employees (
    employee_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    company_member_id bigint REFERENCES company_members(id) ON DELETE SET NULL,
    full_name varchar(100) NOT NULL,
    id_card varchar(200),
    date_of_birth date NOT NULL,
    gender varchar(10) NOT NULL,
    address varchar(255),
    phone varchar(200),
    hire_date date NOT NULL,
    status varchar(50) DEFAULT 'ACTIVE',
    base_salary numeric(15, 2) DEFAULT 0.00,
    allowance numeric(15, 2) DEFAULT 0.00,
    leave_balance integer DEFAULT 12
);

CREATE TABLE leave_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    employee_id bigint NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    leave_type varchar(30) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    total_days integer NOT NULL,
    reason varchar(500),
    status varchar(30) DEFAULT 'PENDING',
    approval_note varchar(500),
    pm_note varchar(500),
    accounting_note varchar(500)
);

CREATE TABLE projects (
    project_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    key_project varchar(10) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    description text,
    status varchar(30) DEFAULT 'ACTIVE',
    is_active boolean NOT NULL DEFAULT true,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    created_by bigint NOT NULL REFERENCES users(user_id),
    start_date date,
    end_date date
);

CREATE TABLE project_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    project_id bigint NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    role varchar(30) NOT NULL DEFAULT 'MEMBER',
    position varchar(100),
    allocation_rate integer,
    member_status varchar(20) DEFAULT 'ACTIVE',
    join_date date,
    leave_date date,
    years_of_experience integer,
    billing_rate numeric(10, 2),
    skill_notes varchar(500),
    CONSTRAINT unique_project_user UNIQUE (project_id, user_id)
);

CREATE TABLE sprints (
    sprint_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    project_id bigint NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    goal text,
    start_date date,
    end_date date,
    status varchar(20) NOT NULL DEFAULT 'PLANNING',
    created_by bigint NOT NULL REFERENCES users(user_id)
);

CREATE TABLE project_phases (
    phase_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    project_id bigint NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    description text,
    start_date date,
    end_date date,
    status varchar(20) NOT NULL DEFAULT 'PLANNING',
    order_index integer DEFAULT 0
);

CREATE TABLE issue_statuses (
    status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    order_index integer NOT NULL,
    color varchar(20)
);

CREATE TABLE issues (
    issue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    project_id bigint NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    sprint_id bigint REFERENCES sprints(sprint_id) ON DELETE SET NULL,
    phase_id bigint REFERENCES project_phases(phase_id) ON DELETE SET NULL,
    issue_key varchar(20) NOT NULL UNIQUE,
    title varchar(255) NOT NULL,
    description text,
    status_id integer NOT NULL REFERENCES issue_statuses(status_id),
    priority varchar(20) NOT NULL DEFAULT 'MEDIUM',
    issue_type varchar(20) DEFAULT 'TASK',
    order_index integer DEFAULT 0,
    reporter_id bigint NOT NULL REFERENCES users(user_id),
    assignee_id bigint REFERENCES users(user_id) ON DELETE SET NULL,
    estimated_hours numeric(5, 2),
    actual_hours numeric(5, 2),
    start_date date,
    due_date date,
    weight integer DEFAULT 1,
    is_important boolean DEFAULT false,
    is_urgent boolean DEFAULT false,
    completed_at timestamp(6),
    rework_count integer DEFAULT 0
);

CREATE TABLE time_logs (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id bigint NOT NULL REFERENCES issues(issue_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    logged_hours numeric(5, 2) NOT NULL,
    work_date date NOT NULL,
    description text,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);

CREATE TABLE issue_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    issue_id bigint NOT NULL REFERENCES issues(issue_id) ON DELETE CASCADE,
    author_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content text NOT NULL
);

CREATE TABLE issue_activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    issue_id bigint NOT NULL REFERENCES issues(issue_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    activity_type varchar(50) NOT NULL,
    field_name varchar(100),
    old_value text,
    new_value text,
    description text
);

CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action varchar(50) not null,
    created_at timestamp(6) not null,
    entity_id bigint,
    entity_type varchar(50),
    error_message TEXT,
    ip_address varchar(50),
    new_value TEXT,
    old_value TEXT,
    reason VARCHAR(1000),
    severity varchar(20) not null check (severity in ('INFO','WARNING','CRITICAL')),
    status varchar(20) not null check (status in ('SUCCESS','FAILED')),
    user_agent varchar(500),
    actor_id bigint not null REFERENCES users(user_id) ON DELETE CASCADE,
    target_user_id bigint REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE calendar_events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    all_day boolean,
    color_code varchar(7),
    created_at timestamp(6) not null,
    description TEXT,
    end_time timestamp(6) not null,
    event_type varchar(20) check (event_type in ('MEETING','DEADLINE','REMINDER','HOLIDAY','OTHER')),
    location VARCHAR(255),
    meeting_link varchar(500),
    recurrence_rule varchar(255),
    start_time timestamp(6) not null,
    title VARCHAR(255) not null,
    updated_at timestamp(6),
    company_id bigint REFERENCES companies(company_id) ON DELETE CASCADE,
    created_by bigint not null REFERENCES users(user_id) ON DELETE CASCADE,
    issue_id bigint REFERENCES issues(issue_id) ON DELETE SET NULL,
    project_id bigint REFERENCES projects(project_id) ON DELETE SET NULL
);

CREATE TABLE project_expenses (
    expense_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    project_id bigint NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    expense_name varchar(200) NOT NULL,
    amount numeric(15,2) NOT NULL,
    expense_date date NOT NULL,
    category varchar(100),
    description TEXT,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    created_by bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE workspace_join_requests (
    request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by bigint REFERENCES users(user_id) ON DELETE SET NULL,
    UNIQUE(company_id, user_id)
);

CREATE TABLE reviews (
    review_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    employee_id bigint NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    reviewer_id bigint NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    project_id bigint,
    project_name varchar(200),
    review_period varchar(50) NOT NULL,
    review_type varchar(30) NOT NULL,
    technical_score numeric(3, 1),
    attitude_score numeric(3, 1),
    soft_skills_score numeric(3, 1),
    teamwork_score numeric(3, 1),
    total_score numeric(3, 1),
    rating varchar(20),
    comments text,
    next_goals text,
    development_plan text,
    status varchar(20) NOT NULL DEFAULT 'IN_PROGRESS',
    start_date date,
    end_date date,
    completed_date date
);

-- ============================================================================
-- 3. GLOBAL SEED DATA SETUP
-- ============================================================================

-- 3.1. Issue Statuses
INSERT INTO issue_statuses (status_id, name, order_index, color) VALUES
(1, 'To Do', 1, '#E2E8F0'),
(2, 'In Progress', 2, '#4BADE8'),
(3, 'Review', 3, '#F6AD55'),
(4, 'Done', 4, '#48BB78');

-- 3.2. Users (12 Users with Hashed Password "Admin@123")
INSERT INTO users (user_id, username, password_hash, email, is_active, is_deleted, is_online, is_system_admin, status, avatar_data, created_at, updated_at) VALUES
(1, 'sysadmin', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'sysadmin@system.com', true, false, false, true, 'ACTIVE', 'https://ui-avatars.com/api/?name=Nguyen+Hung&background=7c3aed&color=fff&size=128', NOW(), NOW()),
(2, 'owner_a', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'owner@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=The+Anh&background=0ea5e9&color=fff&size=128', NOW(), NOW()),
(3, 'admin_a', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'admin@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Hoang+Nam&background=f43f5e&color=fff&size=128', NOW(), NOW()),
(4, 'hr_a', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'hr@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Tuyet+Mai&background=8b5cf6&color=fff&size=128', NOW(), NOW()),
(5, 'acc_a', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'accounting@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Thanh+Son&background=f97316&color=fff&size=128', NOW(), NOW()),
(6, 'pm_a', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'pm@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Minh+Tri&background=14b8a6&color=fff&size=128', NOW(), NOW()),
(7, 'dev_a1', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'dev1@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Quoc+Bao&background=3b82f6&color=fff&size=128', NOW(), NOW()),
(8, 'dev_a2', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'dev2@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Song+Hao&background=10b981&color=fff&size=128', NOW(), NOW()),
(9, 'dev_a3', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'dev3@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Huy+Khanh&background=f59e0b&color=fff&size=128', NOW(), NOW()),
(10, 'dev_a4', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'dev4@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Dinh+Khoa&background=ec4899&color=fff&size=128', NOW(), NOW()),
(11, 'dev_a5', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'qa@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Thuy+Trang&background=a855f7&color=fff&size=128', NOW(), NOW()),
(12, 'full_emp', '$2a$10$AlsxFCJZEN21Uf4a5VIpgey09u7LsnmVYvti93p0h89comm///RwO', 'fullemp@techcorp.vn', true, false, false, false, 'ACTIVE', 'https://ui-avatars.com/api/?name=Van+Dat&background=ef4444&color=fff&size=128', NOW(), NOW());

-- 3.3. Companies
INSERT INTO companies (company_id, name, description, slug, is_active, email, phone, address, subscription_plan, created_at, updated_at) VALUES
(1, 'Tech Corp', 'Công ty Cổ phần Giải pháp Công nghệ Tech Corp', 'tech-corp', true, 'info@techcorp.vn', '02839998888', 'Tầng 12, Tòa nhà Bitexco Financial Tower, 2 Hải Triều, Bến Nghé, Quận 1, TP. Hồ Chí Minh', 'ENTERPRISE', NOW(), NOW());

-- 3.4. Company Settings
INSERT INTO company_settings (company_id, auto_review_enabled, review_cycle_type, google_drive_access_token, google_drive_refresh_token, drive_folder_id, created_at, updated_at) VALUES
(1, false, 'QUARTERLY', NULL, NULL, NULL, NOW(), NOW());

-- 3.5. Company Members
INSERT INTO company_members (id, user_id, company_id, is_active, joined_at, permissions, created_at, updated_at) VALUES
(1, 2, 1, true, NOW() - INTERVAL '6 months', '{}', NOW() - INTERVAL '6 months', NOW() - INTERVAL '6 months'),
(2, 3, 1, true, NOW() - INTERVAL '6 months', '{}', NOW() - INTERVAL '6 months', NOW() - INTERVAL '6 months'),
(3, 4, 1, true, NOW() - INTERVAL '5 months', '{"hrViewList":true,"hrEditProfile":true,"hrCreateEmployee":true,"hrDeleteEmployee":true,"hrManageContracts":true,"hrManageReviews":true,"hrViewDepartments":true,"hrManageDepartments":true,"hrViewPositions":true,"hrManagePositions":true,"hrViewDashboard":true,"hrExport":true,"projectCreate":true,"projectManageIssues":true,"projectViewDashboard":true,"reviewViewAll":true,"reviewCreate":true,"reviewApprove":true}', NOW() - INTERVAL '5 months', NOW() - INTERVAL '5 months'),
(4, 5, 1, true, NOW() - INTERVAL '5 months', '{}', NOW() - INTERVAL '5 months', NOW() - INTERVAL '5 months'),
(5, 6, 1, true, NOW() - INTERVAL '4 months', '{"projectCreate":true,"projectManageAll":true,"projectDelete":true,"projectManageIssues":true,"projectManageSprints":true,"projectViewDashboard":true,"projectExport":true,"projectManagePhases":true,"projectResourcePlanning":true,"hrViewList":true,"hrViewDepartments":true,"hrViewPositions":true,"hrViewDashboard":true}', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months'),
(6, 7, 1, true, NOW() - INTERVAL '4 months', '{}', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months'),
(7, 8, 1, true, NOW() - INTERVAL '4 months', '{}', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months'),
(8, 9, 1, true, NOW() - INTERVAL '4 months', '{}', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months'),
(9, 10, 1, true, NOW() - INTERVAL '3 months', '{}', NOW() - INTERVAL '3 months', NOW() - INTERVAL '3 months'),
(10, 11, 1, true, NOW() - INTERVAL '3 months', '{}', NOW() - INTERVAL '3 months', NOW() - INTERVAL '3 months'),
(11, 12, 1, true, NOW() - INTERVAL '6 months', '{"workspaceManageMembers":true,"workspaceManageRequests":true,"hrViewList":true,"hrEditProfile":true,"hrCreateEmployee":true,"hrDeleteEmployee":true,"hrManageReviews":true,"hrViewDashboard":true,"hrExport":true,"projectCreate":true,"projectDelete":true,"projectManageAll":true,"projectManageIssues":true,"projectManageSprints":true,"projectManagePhases":true,"projectResourcePlanning":true,"projectViewDashboard":true,"projectExport":true,"timetrackingLog":true,"timetrackingViewAll":true,"leaveApprove":true,"leaveViewAll":true,"analyticsView":true,"calendarView":true,"calendarManage":true,"reviewViewAll":true,"reviewCreate":true,"reviewApprove":true}', NOW() - INTERVAL '6 months', NOW() - INTERVAL '6 months');

-- 3.6. Company Member Roles
INSERT INTO company_member_roles (id, member_id, role) VALUES
(1, 1, 'OWNER'),
(2, 2, 'COMPANY_ADMIN'),
(3, 3, 'EMPLOYEE'),
(4, 4, 'EMPLOYEE'),
(5, 5, 'EMPLOYEE'),
(6, 6, 'EMPLOYEE'),
(7, 7, 'EMPLOYEE'),
(8, 8, 'EMPLOYEE'),
(9, 9, 'EMPLOYEE'),
(10, 10, 'EMPLOYEE'),
(11, 11, 'EMPLOYEE');
