-- ============================================================================
-- GEMINI ERP - OBSOLETE FILE
-- Description: Indexes are automatically created by Hibernate/JPA using @Index
-- annotations on startup. Manual index seeding is no longer required.
-- ============================================================================
