-- ============================================================================
-- MIGRATION: Add missing tables and columns (VERIFIED & ALIGNED WITH BE ENTITIES)
-- Generated based on rigorous entity-to-database schema analysis
-- ============================================================================

-- ── 1. MISSING COLUMNS on existing tables ────────────────────────────────────

-- issues: missing columns from Issue entity
ALTER TABLE issues ADD COLUMN IF NOT EXISTS total_score numeric(3,1);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS ai_score numeric(3,1);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS human_score numeric(3,1);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS priority_coefficient numeric(3,2) DEFAULT 1.0;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS issue_category varchar(50);

-- projects: missing columns from Project entity
ALTER TABLE projects ADD COLUMN IF NOT EXISTS budget numeric(15,2);

-- company_members: missing columns from CompanyMember entity
ALTER TABLE company_members ADD COLUMN IF NOT EXISTS invited_at timestamp(6);
ALTER TABLE company_members ADD COLUMN IF NOT EXISTS invited_by varchar(100);
-- permissions column: update to NVARCHAR(MAX) for UserPermissions JSON
ALTER TABLE company_members ALTER COLUMN permissions TYPE TEXT;

-- users: missing notification columns (embedded NotificationSettings)
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_email_new_message boolean DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_email_mentions boolean DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_email_weekly_digest boolean DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_push_desktop boolean DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_push_mobile boolean DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_sound_enabled boolean DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_email_project_updates boolean DEFAULT true;

-- ── 2. MISSING TABLES ────────────────────────────────────────────────────────

-- notifications
CREATE TABLE IF NOT EXISTS notifications (
    notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    type varchar(50) NOT NULL,
    title varchar(255) NOT NULL,
    content varchar(500),
    link varchar(500),
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp(6),
    priority varchar(20) DEFAULT 'NORMAL',
    metadata TEXT
);
CREATE INDEX IF NOT EXISTS idx_notif_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notif_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notif_type ON notifications(type);
CREATE INDEX IF NOT EXISTS idx_notif_created ON notifications(created_at);

-- project_goals
CREATE TABLE IF NOT EXISTS project_goals (
    goal_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    title varchar(500) NOT NULL,
    month_value integer NOT NULL,
    year_value integer NOT NULL,
    is_completed boolean NOT NULL DEFAULT false,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);
CREATE INDEX IF NOT EXISTS idx_goal_project ON project_goals(project_id);

-- issue_custom_fields
CREATE TABLE IF NOT EXISTS issue_custom_fields (
    field_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    name varchar(100) NOT NULL,
    description varchar(255),
    field_type varchar(20) NOT NULL,
    options text,
    is_required boolean DEFAULT false,
    display_order integer DEFAULT 0,
    is_active boolean DEFAULT true,
    default_value varchar(500),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);
CREATE INDEX IF NOT EXISTS idx_customfield_project ON issue_custom_fields(project_id);
CREATE INDEX IF NOT EXISTS idx_customfield_company ON issue_custom_fields(company_id);

-- issue_custom_field_values
CREATE TABLE IF NOT EXISTS issue_custom_field_values (
    value_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id bigint NOT NULL REFERENCES issues(issue_id) ON DELETE CASCADE,
    field_id bigint NOT NULL REFERENCES issue_custom_fields(field_id) ON DELETE CASCADE,
    string_value text,
    number_value numeric(18, 4),
    date_value date,
    datetime_value timestamp(6),
    boolean_value boolean,
    user_value bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    UNIQUE(issue_id, field_id)
);
CREATE INDEX IF NOT EXISTS idx_cfv_issue ON issue_custom_field_values(issue_id);
CREATE INDEX IF NOT EXISTS idx_cfv_field ON issue_custom_field_values(field_id);

-- issue_dependencies
CREATE TABLE IF NOT EXISTS issue_dependencies (
    dependency_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    predecessor_id bigint NOT NULL REFERENCES issues(issue_id) ON DELETE CASCADE,
    successor_id bigint NOT NULL REFERENCES issues(issue_id) ON DELETE CASCADE,
    dependency_type varchar(20) NOT NULL DEFAULT 'FINISH_TO_START',
    lag_days integer DEFAULT 0,
    created_at timestamp(6) NOT NULL,
    UNIQUE(predecessor_id, successor_id)
);
CREATE INDEX IF NOT EXISTS idx_dep_predecessor ON issue_dependencies(predecessor_id);
CREATE INDEX IF NOT EXISTS idx_dep_successor ON issue_dependencies(successor_id);

-- project_expenses (with tenant isolation via company_id)
CREATE TABLE IF NOT EXISTS project_expenses (
    expense_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    expense_name varchar(200) NOT NULL,
    amount numeric(15,2) NOT NULL,
    expense_date date NOT NULL,
    category varchar(100),
    description TEXT,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    created_by bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);
CREATE INDEX IF NOT EXISTS idx_expense_project ON project_expenses(project_id);

-- resource_allocations (per-entity allocation, no company_id)
CREATE TABLE IF NOT EXISTS resource_allocations (
    allocation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    project_id bigint REFERENCES projects(project_id) ON DELETE CASCADE,
    start_date date NOT NULL,
    end_date date NOT NULL,
    allocation integer NOT NULL,
    note varchar(500),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);
CREATE INDEX IF NOT EXISTS idx_alloc_project ON resource_allocations(project_id);
CREATE INDEX IF NOT EXISTS idx_alloc_employee ON resource_allocations(employee_id);

-- salary_proposals
CREATE TABLE IF NOT EXISTS salary_proposals (
    proposal_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    company_id bigint REFERENCES companies(company_id) ON DELETE CASCADE,
    project_id bigint,
    proposed_salary numeric(15,2) NOT NULL,
    current_salary numeric(15,2),
    reason TEXT,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by bigint REFERENCES users(user_id) ON DELETE SET NULL,
    review_date date,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);
CREATE INDEX IF NOT EXISTS idx_proposal_employee ON salary_proposals(employee_id);

-- refresh_tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token varchar(500) NOT NULL UNIQUE,
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    expires_at timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL,
    is_revoked boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_rt_user ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_rt_expires ON refresh_tokens(expires_at);

-- user_sessions
CREATE TABLE IF NOT EXISTS user_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    session_id varchar(100) NOT NULL UNIQUE,
    ip_address varchar(45),
    user_agent varchar(500),
    created_at timestamp(6) NOT NULL,
    last_activity timestamp(6) NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS idx_us_user ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_us_active ON user_sessions(is_active);
CREATE INDEX IF NOT EXISTS idx_us_lastactivity ON user_sessions(last_activity);

-- login_attempts
CREATE TABLE IF NOT EXISTS login_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50),
    ip_address varchar(45),
    success boolean NOT NULL,
    failure_reason varchar(200),
    attempted_at timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_la_username_time ON login_attempts(username, attempted_at);
CREATE INDEX IF NOT EXISTS idx_la_ip ON login_attempts(ip_address);

-- files
CREATE TABLE IF NOT EXISTS files (
    file_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name varchar(255) NOT NULL,
    google_drive_file_id varchar(255) NOT NULL,
    file_size bigint,
    content_type varchar(255),
    project_id bigint REFERENCES projects(project_id) ON DELETE SET NULL,
    issue_id bigint REFERENCES issues(issue_id) ON DELETE SET NULL,
    uploaded_by bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    folder varchar(255),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);
CREATE INDEX IF NOT EXISTS idx_file_uploader ON files(uploaded_by);
CREATE INDEX IF NOT EXISTS idx_file_project ON files(project_id);

-- global_settings
CREATE TABLE IF NOT EXISTS global_settings (
    setting_key varchar(255) PRIMARY KEY,
    setting_value TEXT,
    description TEXT,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);

-- time_logs: add missing columns if not present
ALTER TABLE time_logs ADD COLUMN IF NOT EXISTS notes TEXT;

-- calendar_events: add missing columns
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS is_recurring boolean DEFAULT false;

-- event_attendees (referenced by entity but may be missing)
CREATE TABLE IF NOT EXISTS event_attendees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES calendar_events(event_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    response_status varchar(20) DEFAULT 'PENDING',
    UNIQUE(event_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_attendee_event ON event_attendees(event_id);
CREATE INDEX IF NOT EXISTS idx_attendee_user ON event_attendees(user_id);
