-- ============================================================================
-- GEMINI ERP - OBSOLETE FILE
-- Description: The newly generated 02_seed_data.sql contains perfectly aligned
-- sprint and issue mappings. Backlog tasks are correctly organized, making this
-- fix script obsolete.
-- ============================================================================
