package DoAn.BE.notification.entity;

public enum NotificationType {
    // SYSTEM
    SYSTEM_ALERT,

    // AUTH
    AUTH_LOGIN_NEW_DEVICE,
    AUTH_PASSWORD_CHANGED,

    // HR - ATTENDANCE
    HR_ATTENDANCE_CHECKIN,
    HR_ATTENDANCE_CHECKOUT,
    HR_ATTENDANCE_LATE,
    HR_ATTENDANCE_FORGOT_CHECKOUT,
    HR_ATTENDANCE_MISSING,
    HR_ATTENDANCE_OUT_OF_RANGE,
    HR_ATTENDANCE_SUMMARY,
    HR_ATTENDANCE_REMINDER,

    // HR - LEAVE
    HR_LEAVE_REQUEST_CREATED,
    HR_LEAVE_APPROVED,
    HR_LEAVE_REJECTED,

    // HR - SALARY
    HR_SALARY_CREATED,
    HR_SALARY_APPROVED,
    HR_SALARY_PAID,
    HR_SALARY_INCREASE_PROPOSAL,
    HR_SALARY_INCREASE_RESULT,

    // HR - OTHER
    HR_BIRTHDAY,
    HR_BIRTHDAY_SELF,

    // HR - CONTRACT
    HR_CONTRACT_EXPIRING,

    // PROJECT
    PROJECT_ASSIGNED,
    PROJECT_UPDATE,
    PROJECT_ISSUE,
    PROJECT_SPRINT,
    TASK_ASSIGNED,
    TASK_DUE_SOON,

    // STORAGE
    STORAGE_UPDATE,
    STORAGE_QUOTA,

    // CHAT
    CHAT_MESSAGE,
    CHAT_ROOM,
    CHAT_MENTION,
    CHAT_TASK_MENTION,
    CHAT_MESSAGE_EDITED,
    CHAT_MESSAGE_DELETED
}
